# Generated by Django 5.2.12 on 2026-03-05 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bike',
            options={'verbose_name': 'Bike', 'verbose_name_plural': 'Bikes'},
        ),
        migrations.AlterModelOptions(
            name='bikestatus',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Bike Status', 'verbose_name_plural': 'Bike Statuses'},
        ),
        migrations.AddField(
            model_name='bike',
            name='emergency_name',
            field=models.CharField(default='Emergency Contact', max_length=100),
        ),
        migrations.AddField(
            model_name='bike',
            name='emergency_number',
            field=models.CharField(default='+910000000000', max_length=20),
        ),
        migrations.AddField(
            model_name='bike',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bike',
            name='last_heartbeat',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bike',
            name='silent_mode',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bikestatus',
            name='fsr',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bikestatus',
            name='impact_force',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='bikestatus',
            name='tilt_angle',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='bikestatus',
            name='vibration',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bikestatus',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='bikestatus',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=10),
        ),
        migrations.CreateModel(
            name='AccidentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scenario', models.IntegerField(choices=[(1, 'Parked Bike Hit'), (2, 'Minor Collision'), (3, 'Major Crash - Rider Conscious'), (4, 'Major Crash - Rider Unresponsive')], default=4)),
                ('latitude', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('was_cancelled', models.BooleanField(default=False)),
                ('sms_sent', models.BooleanField(default=False)),
                ('call_made', models.BooleanField(default=False)),
                ('emergency_number_used', models.CharField(blank=True, max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('bike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accidents', to='core.bike')),
            ],
            options={
                'verbose_name': 'Accident Log',
                'verbose_name_plural': 'Accident Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
